<?php

/*****
 * Name: ElearnTables.php
 * Date: 2013-06-02
 *
 * This is a mid-level, interface class that sits between Query2 and
 * ElearnQuery. Its sole purpose is to house the elearn tables in a hashed
 * array.  It is generated by /home/project/tables.php
 *****/

include_once("Query2.php");

class ElearnTables extends Query2 {
    public $wally_tables = array();
    public function __construct($d=null, $u=null, $p=null, $db=null) {
        parent::__construct($d, $u, $p, $db);
        $this->LoadTables();
    }
    public function __destruct() {
        parent::__destruct();
    }
    protected function LoadTables() {
        $tables = array();
        $this->wally_tables = $tables;
    }
}

?>